### ISSUE TITLE
Can't seem to load the app with 'meteor'

### ISSUE THREAD

**Issue by JulianSamarjiev** [zhongqf/meteor-react-redux-example#1]
Hey @zhongqf , I can't seem to be able to get the app running, I cloned the repo and ran 'meteor' to install all the npm dependencies, but it's showing a blank page and no errors in the terminal or the console, any tips on how I can get it running? 
Great work by the way, been looking for a long time for a react-meteor-redux implementation example, thanks!

**Comment by djhi** [comment]
```
cd .client
npm install
webpack
cd ..
meteor
```

Voila ! 

I'll submit a makefile for this

**Comment by JulianSamarjiev** [comment]
@djhi Thanks for the answer, will try it out tonight, looks good.

**Comment by djhi** [comment]
I just submited a PR for this. 

@zhongqf: thx for this demo !

**Comment by zhongqf** [comment]
Thanks, @djhi , I will accept your PR.
Sorry for late response.  :smile: 

@JulianSamarjiev @djhi
